=== alumraulgago/Examen_UD4/datos.dtd
<!ELEMENT datos (almacen*)>
<!ELEMENT alamcen (sucursal, articulos)>
<!ALLIST sucursal (codigo_sucursal, nombre_trabajador, fecha_pedido, observaciones, direccion?)>
<!ELEMENT codigo_sucursal (#PCDATA)>
<!ELEMENT nombre_trabajador (#PCDATA)>
<!ELEMENT fecha_pedido (#PCDATA)>
<!ELEMENT observaciones (#PCDATA)>
<!ELEMENT direccion (#PCDATA)>
<!ALLIST articulos (codigo_articulo, numero_pedido, precio, observaciones, plazo)>
<!ELEMENT codigo_articulo (#PCDATA)>
<!ELEMENT numero_pedido (#PCDATA)>
<!ELEMENT precio (#PCDATA)>
<!ELEMENT observaciones (#PCDATA)>
<!ELEMENT plazo (#PCDATA)>

=== alumraulgago/Examen_UD4/sucursal.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE datos SYSTEM "datos.dtd">

<datos>
    <almacen>
        <sucursal>
            <codigo_sucursal>A8785843</codigo_sucursal>
            <nombre_trabajador>Juan</nombre_trabajador>
            <fecha_pedido>28/06/2018</fecha_pedido>
            <observaciones></observaciones>
            <direccion></direccion>
        </sucursal>
        <articulos>
            <codigo_articulo>NTR-987</codigo_articulo>
            <numero_pedido>40</numero_pedido>
            <precio>1200.00</precio>
            <observaciones>Es un pedido de juguetes</observaciones>
            <plazo>80</plazo>
        </articulos>
        <sucursal>
            <codigo_sucursal>A8785843</codigo_sucursal>
            <nombre_trabajador>Juan</nombre_trabajador>
            <fecha_pedido>28/06/2018</fecha_pedido>
            <observaciones></observaciones>
            <direccion></direccion>
        </sucursal>
        <articulos>
            <codigo_articulo>NTR-987</codigo_articulo>
            <numero_pedido>40</numero_pedido>
            <precio>1200.00</precio>
            <observaciones>Es un pedido de juguetes</observaciones>
            <plazo>80</plazo>
        </articulos>
    </almacen>
</datos>
